version: 1.0.{build}

image: 
  - Ubuntu
  - Visual Studio 2017

platform:
  - x64

environment:
  matrix:
    - nodejs_version: "16"
    - nodejs_version: "14"
    - nodejs_version: "12"

  test_script:
    - ps: Write-Host "jspurefix test script"    

  for:
  -
      matrix:
        only:
          - image: Visual Studio 2017
    
      clone_folder: c:\projects\jspurefix

      install:
        - ps: Install-Product node $env:nodejs_version $env:platform
        - npm install

      build_script:
        - node --version
        - cmd: script\build.cmd

      test_script:
        - cmd: script\test.cmd
  -        
      matrix:
        only:
          - image: Ubuntu
          - platform: x64

      clone_folder: /home/appveyor/projects/jspurefix 
      
      install:
        - nvm install $nodejs_version
        - npm install

      build_script:
        - node --version
        - sh: script/build.sh

      test_script:
        - sh: "npm run tcp-tc"
        - sh: "npm run http-oms"
        - sh: "npm run t"

